services:
  - type: web
    name: xch
    env: python
    plan: free   # 有料にするなら「starter」や「standard」
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
